[package]
name = "sphere-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
itertools = "0.11.0"
num = "0.4.1"
rayon = "1.8.0"

